version: '2'

services:
  reverse_exporter:
    build: .
    command: --log-level=debug
    ports:
    - 127.0.0.1:9998:9998
    volumes:
      - ./reverse_exporter.compose.yml:/config/reverse_exporter.yml
    
  prometheus:
    image: quay.io/prometheus/prometheus
  
  node_exporter:
    image: quay.io/prometheus/node-exporter
    privileged: true
    
